AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 Event-Driven Architecture with Lambda & SNS

# Parameters to support different environments
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment environment (dev or prod)

  EmailAddress:
    Type: String
    Description: Email address to receive notifications

# Resources for our application
Resources:
  # Lambda function to process uploads
  FileUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub file-upload-processor-${Environment}
      CodeUri: HelloWorldFunction/
      Handler: helloworld.App
      Runtime: java21
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref NotificationTopic
          ENVIRONMENT: !Ref Environment
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt NotificationTopic.TopicName
        - S3ReadPolicy:
            BucketName: !Sub s3-upload-bucket-${Environment}-${AWS::AccountId}

  # SNS Topic for notifications
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub file-upload-notifications-${Environment}
      DisplayName: !Sub "File Upload Notifications - ${Environment}"

  # SNS Subscription for email
  EmailNotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref EmailAddress
      TopicArn: !Ref NotificationTopic

  # Lambda permission to allow S3 to invoke it
  FileUploadPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref FileUploadFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::s3-upload-bucket-${Environment}-${AWS::AccountId}
      SourceAccount: !Ref AWS::AccountId

  # S3 Bucket for file uploads
  UploadBucket:
    Type: AWS::S3::Bucket
    DependsOn: FileUploadPermission
    Properties:
      BucketName: !Sub s3-upload-bucket-${Environment}-${AWS::AccountId}
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt FileUploadFunction.Arn


# Outputs for easy reference
Outputs:
  UploadBucketName:
    Description: Name of the S3 bucket for file uploads
    Value: !Ref UploadBucket

  NotificationTopicArn:
    Description: ARN of the SNS topic for notifications
    Value: !Ref NotificationTopic

  LambdaFunctionName:
    Description: Name of the Lambda function processing uploads
    Value: !Ref FileUploadFunction